### PR TITLE
Made changes in scott dick controller to incorporate movement

### PR DESCRIPTION
**Pull request by AidenTeal**

### CODE REVIEW

**Review by Cedric-Boucher — CHANGES_REQUESTED** [review]
Why were all the type hints, removal of unused imports, improved comments and minor improvements I had added undone?

**Review by Cedric-Boucher — APPROVED** [review]
looks good

**Comment by Cedric-Boucher** [comment]
@AidenTeal do you want to merge this into main or just start off of my branch where I set up the genetic fuzzy system?

**Comment by AidenTeal** [comment]
@Cedric-Boucher If you have our controller setup with the genetic stuff, I guess will just not accept this PR. Just let me know when your branch is ready to be merged into main, and then I will integrate my movement code into the controller with the genetic algorithm. Then I can make a PR for that. I may not be able to do it tonight though.

**Pull request closed without merging**
